-- INVENTORY DATA
INSERT INTO INVENTORY VALUES (N'Kho Tổng');
-- CATEGORY DATA
INSERT INTO CATEGORY VALUES ('IPhone',GETDATE(),NULL,NULL,NULL,'True','False');
INSERT INTO CATEGORY VALUES ('Mac',GETDATE(),NULL,NULL,NULL, 'True','False');
INSERT INTO CATEGORY VALUES ('Ipad',GETDATE(),NULL,NULL,NULL, 'True','False');
INSERT INTO CATEGORY VALUES ('Watch',GETDATE(),NULL,NULL,NULL, 'True','False');
INSERT INTO CATEGORY VALUES (N'Âm thanh',GETDATE(),NULL,NULL,NULL, 'True','False');
-- IPHONE 15 PRO MAX
INSERT INTO PRODUCT VALUES (N'Điện thoại iPhone 15 Plus (128GB) - Chính hãng VN/A', '128 GB', 26590000, 24590000,'Detail product',GETDATE(),NULL,NULL,NULL,'True', 'False',1,'/Images/Products/iphone-15-plus-blue.png');
INSERT INTO PRODUCT VALUES (N'Điện thoại iPhone 15 Plus (256GB) - Chính hãng VN/A', '256 GB', 29590000, 27590000,'Detail product',GETDATE(),NULL,NULL,NULL,'True', 'False',1,'/Images/Products/iphone-15-plus-pink.png');
INSERT INTO PRODUCT VALUES (N'Điện thoại iPhone 15 Pro (512GB) - Chính hãng VN/A', '512 GB', 38490000, 36490000,'Detail product',GETDATE(),NULL,NULL,NULL,'True', 'False',1,'/Images/Products/test.png');
-- IPAD PRO
INSERT INTO PRODUCT VALUES (N'Máy tính bảng iPad Pro M2 11" 5G (128GB) - Chính hãng Apple Việt Nam', '128 GB', 26590000, 23590000,'Detail product',GETDATE(),NULL,NULL,NULL,'True', 'False',3,'/Images/Products/test2.png');
INSERT INTO PRODUCT VALUES (N'Máy tính bảng iPad Pro M2 11" 5G (256GB) - Chính hãng Apple Việt Nam', '256 GB', 28990000, 26990000,'Detail product',GETDATE(),NULL,NULL,NULL,'True', 'False',3,'/Images/Products/test2.png');
INSERT INTO PRODUCT VALUES (N'Máy tính bảng iPad Pro M2 11" 5G (512GB) - Chính hãng Apple Việt Nam', '512 GB', 36990000, 33990000,'Detail product',GETDATE(),NULL,NULL,NULL,'True', 'False',3,'/Images/Products/test2.png');
--SEED ROLE
INSERT INTO [ROLE] VALUES ('User');
INSERT INTO [ROLE] VALUES ('Admin');
INSERT INTO [ROLE] VALUES ('Shiper');
-- SEED ACCOUNT

INSERT INTO ACCOUNT VALUES ('Admin','áÜ9IºY«¾VàWòˆ>','Admin@gmail.com','ADMIN','06 Vu Trong Phung','0909000999','01-01-1998',NULL,GETDATE(),NULL,NULL,'False','True','False',2);
INSERT INTO ACCOUNT VALUES ('Shipper','áÜ9IºY«¾VàWòˆ>','Shipper@gmail.com','USER1','05 Vu Trong Phung','0909000888','02-01-1998',NULL,GETDATE(),NULL,NULL,'False','True','False',3);

-- SALE
INSERT INTO SALE VALUES(1,10,20000000,GETDATE(),NULL,'Admin@gmail.com',NULL,'False');
INSERT INTO SALE VALUES(2,10,25590000,GETDATE(),NULL,'Admin@gmail.com',NULL,'False');
INSERT INTO SALE VALUES(3,10,30490000,GETDATE(),NULL,'Admin@gmail.com',NULL,'False');
INSERT INTO SALE VALUES(4,10,20590000,GETDATE(),NULL,'Admin@gmail.com',NULL,'False');
INSERT INTO SALE VALUES(5,10,22990000,GETDATE(),NULL,'Admin@gmail.com',NULL,'False');
INSERT INTO SALE VALUES(6,10,30990000,GETDATE(),NULL,'Admin@gmail.com',NULL,'False');
-- INVENTORY DETAIL
INSERT INTO INVENTORYDETAIL VALUES(GETDATE(), 10, 0, 10, 1,1);
INSERT INTO INVENTORYDETAIL VALUES(GETDATE(), 10, 0, 10, 2,1);
INSERT INTO INVENTORYDETAIL VALUES(GETDATE(), 10, 0, 10, 3,1);
INSERT INTO INVENTORYDETAIL VALUES(GETDATE(), 10, 0, 10, 4,1);
INSERT INTO INVENTORYDETAIL VALUES(GETDATE(), 10, 0, 10, 5,1);
INSERT INTO INVENTORYDETAIL VALUES(GETDATE(), 10, 0, 10, 6,1);

--ORDER
INSERT INTO [ORDER] VALUES (24590000,GETDATE(),NULL,'User1@gmail.com',NULL,N'01 Nguyễn Hữu Thọ',NULL,N'Đã đặt hàng','False',2);
INSERT INTO [ORDERDETAIL] VALUES (1,1,24590000,1);
INSERT INTO [ORDER] VALUES (52180000,GETDATE(),NULL,'User1@gmail.com',NULL,N'01 Nguyễn Hữu Thọ',NULL,N'Đã đặt hàng','False',2);
INSERT INTO [ORDERDETAIL] VALUES (1,1,24590000,2);
INSERT INTO [ORDERDETAIL] VALUES (2,1,27590000,2);
---
INSERT INTO [ORDER] VALUES (24590000,GETDATE(),NULL,'User1@gmail.com',NULL,N'01 Nguyễn Hữu Thọ',NULL,N'Đã đặt hàng','False',2);
INSERT INTO [ORDERDETAIL] VALUES (1,1,24590000,3);
INSERT INTO [ORDER] VALUES (24590000,GETDATE(),NULL,'User1@gmail.com',NULL,N'01 Nguyễn Hữu Thọ',NULL,N'Đã đặt hàng','False',2);
INSERT INTO [ORDERDETAIL] VALUES (1,1,24590000,4);
INSERT INTO [ORDER] VALUES (24590000,GETDATE(),NULL,'User1@gmail.com',NULL,N'01 Nguyễn Hữu Thọ',NULL,N'Đã đặt hàng','False',2);
INSERT INTO [ORDERDETAIL] VALUES (1,1,24590000,5);
GO
---
INSERT INTO PROMOTION VALUES ('COUPON20',20,GETDATE(), NULL, 'admin@gmail.com',NULL, 'False');
INSERT INTO PROMOTION VALUES ('COUPON30',30,GETDATE(), NULL, 'admin@gmail.com',NULL, 'False');
INSERT INTO PROMOTION VALUES ('COUPON40',40,GETDATE(), NULL, 'admin@gmail.com',NULL, 'False');
INSERT INTO PROMOTION VALUES ('COUPON50ONLY',50,GETDATE(), NULL, 'admin@gmail.com',NULL, 'False');
INSERT INTO PROMOTION VALUES ('COUPON10FORALL',10,GETDATE(), NULL, 'admin@gmail.com',NULL, 'False');
GO
